### ISSUE TITLE
Make available for browser

### ISSUE THREAD

**Issue by hughfdjackson** [dominictarr/curry#6]
As a user (me!) I'd love to use this in an AMD environment, or as a global in browsers, in addition to in node.

Acceptance:
- Use a UMD style wrapping, as here: https://github.com/hughfdjackson/viral/blob/master/viral.js
- Update README to reflect the installation options.

**Comment by dominictarr** [comment]
this already works in the browser - if you use browserify

**Comment by hughfdjackson** [comment]
Tis true - could just run it through browserify with UMD.  Either way, this is just something i tend to do with my tiny libs to lower the bar to adoption a little.

**Comment by dominictarr** [comment]
fair enough, I just like to encourage browserify where I can.

**Comment by hughfdjackson** [comment]
Fixed :)
